Fix compile when HAVE_GPHOTO2 is not defined
digikam/utilities/importui/backend/gpcamera.cpp: In
member function 'virtual bool Digikam::GPCamera::getFolders(const
QString&)':
digikam/utilities/importui/backend/gpcamera.cpp:681:
error: 'subFolderList' was not declared in this scope

Possibly a result of commit c64fea2e8545d97628c282752f74082f2d2e7812